// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1719419237);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1719419216);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1719419212);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1719419357);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1719419267);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1719419206);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0d5f23f4-4dad-4e30-b26a-5c959004b3d0}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1719419209);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1719419270229");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1719421060229");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1719419226318");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1719440826318");
user_pref("browser.search.region", "VN");
user_pref("browser.startup.homepage_override.buildID", "20210415204500");
user_pref("browser.startup.homepage_override.mstone", "88.0");
user_pref("browser.startup.lastColdStartupCheck", 1719419208);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"abb-acer_amazon_com-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"abb-acer_amazon_com-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Bing");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1719419209606");
user_pref("distribution.acer-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "88.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "e17675e2091a4605890fd755b4e2cb2c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.installedDistroAddon.abb-acer@amazon.com", true);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20210415204500");
user_pref("extensions.lastAppVersion", "88.0");
user_pref("extensions.lastPlatformVersion", "88.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.abb-acer@amazon.com", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"abb-acer@amazon.com\":\"9bde7c77-8771-4579-96db-1783d7c72b27\",\"doh-rollout@mozilla.org\":\"3d5fcda5-d0b7-4039-8f5b-bab324eb971c\",\"formautofill@mozilla.org\":\"0d151659-5a7d-42a4-a9b9-b445171ce5a8\",\"pictureinpicture@mozilla.org\":\"cc69c998-ef75-4b49-bfbb-970004798e74\",\"screenshots@mozilla.org\":\"83235eef-a2d6-4e2f-8ce1-b42342de9cba\",\"webcompat-reporter@mozilla.org\":\"07657b5b-737d-41b0-bbd7-0f55269d473a\",\"webcompat@mozilla.org\":\"b949cbc7-c07b-4506-8739-2cbacda7da76\",\"default-theme@mozilla.org\":\"9b94cf7e-6d81-4202-a852-5327cf734cc9\",\"bing@search.mozilla.org\":\"669d7450-c0c1-4407-9c41-d9d1bb1e62fb\",\"amazondotcom@search.mozilla.org\":\"40da3c24-38e0-453c-b375-64dd9ebad7d9\",\"wikipedia@search.mozilla.org\":\"c61805bf-945a-49b3-a4f6-d13b148c0b7b\",\"ddg@search.mozilla.org\":\"ec88c3cc-2f3d-4d80-b256-057e5ea4258b\",\"google@search.mozilla.org\":\"a878c490-4432-4acb-85d6-f158b6482a78\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1719419209);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "88.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x1638");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "27.20.14032.15001");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x1638");
user_pref("sanity-test.driver-version", "27.20.14032.15001");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20210415204500");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{a05b1bc3-6444-4404-9f8c-30f6f7df5255}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{2e4bdc83-fcc2-48bc-9bf0-533142213d25}");
user_pref("toolkit.startup.last_success", 1719419205);
user_pref("toolkit.telemetry.cachedClientID", "b3cd721a-8834-48ad-a7e0-40bbb974ea11");
user_pref("toolkit.telemetry.previousBuildID", "20210415204500");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
